### ISSUE TITLE
App Crashing on Debug

### ISSUE THREAD

**Issue by pranshuchittora** [react-native-community/react-native-template-typescript#198] opened 2021-03-21 23:18 UTC
## Observed results
App crashing of hitting debug

### Logs
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at UnableToResolveError.buildCodeFrameMessage (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /home/undefined/work/round2/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /home/undefined/work/round2/node_modules/metro/src/Server.js:1471:14
    at Generator.next (<anonymous>)
```
Please add the log output here.

## Steps to reproduce

1. Open in Android
2. Hit debug

**Comment by radko93** [comment] 2021-03-22 12:00
Hi, can you try if this also happens without the typescript template?

**Comment by dgellow** [comment] 2021-03-22 18:59
I can confirm that I'm facing the same error. I created a new react native project using the template `react-native-template-typescript` and get this error `Error: EISDIR: illegal operation on a directory, read` after bundling the app.

So far I haven't been able to figure out which directory/file it is trying to read.

**Comment by radko93** [comment] 2021-03-23 09:41
@dgellow can you try to create a project without the template and if you can reproduce it?

**Comment by dgellow** [comment] 2021-03-23 09:48
Hey @radko93. I did this a few minutes ago, and yes I can reproduce without the typescript template.
There are two things:
1.  There is a bug in metro itself (as mentioned in my previous message, see https://github.com/facebook/metro/pull/567)
2. And at least for my case, another bug somewhere else that I haven't located yet.

So it doesn't seem to be related to the typescript template. I believe that we can close this issue, but I'm not the one who created it, and do not know if @pranshuchittora is actually facing the same issue. The symptom look the same because of the bug in metro, but that's it.

**Comment by emin93** [comment] 2021-07-04 09:21
Closing this as this seems to be not related to this template and an issue in the RN repo should be created instead.

**Closed by emin93** 2021-07-04 09:21 UTC
