### ISSUE TITLE
Hot Reloading

### ISSUE THREAD

**Issue by gamingumar** [react-native-community/react-native-template-typescript#48] opened 2019-07-14 11:04 UTC
# Bug
Hot Reloading doesn't seem to be working
## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 82.00 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: x.x.x

## Steps To Reproduce

1. Enable Hot reloading
2. Change some text in App.tsx
...

Describe what you expected to happen:

1. Text should change with hot reloading enabled

## Reproducible sample code

None required

**Comment by toupilsner** [comment] 2019-07-15 14:36
I have the same issue as well (mac).  
Node: 10.15.3
react-native-cli: 2.0.1
react-native: 0.60.3

**Comment by thiagobrez** [comment] 2019-08-14 14:34
I'm also facing the same issue. Any news on this?

Node: v12.6.0
react: v16.8.6
react-native: v0.60.5

**Comment by thiagobrez** [comment] 2019-08-14 15:18
Live reloading is an workaround, but obviously heavier

**Comment by KostasDimakis** [comment] 2019-09-01 15:10
I am facing the same issue as well.

And just to add a bit more context on this. When I make a change to `App.tsx` for example I do see "Hot reloading..." on the emulator but the changes aren't applied.

react: 16.8.6
react-native: 0.60.5
node: 10.15.0

**Comment by KostasDimakis** [comment] 2019-09-06 21:19
Woop! 🎉I tested with `0.61.0-rc.2`, as in `npx react-native init RN061 --version react-native@next --template typescript` and I can confirm that _fast refresh_ is working as intended.

**Comment by osamaq** [comment] 2019-09-15 02:25
As far as I know hot reloading only works with class-based components and not with functional components. Fast Refresh in RN 61 is the solution.

**Comment by KostasDimakis** [comment] 2019-09-15 10:31
When I initially ran into the problem I was using class-based components @osamaq

**Comment by emin93** [comment] 2019-09-25 08:59
As soon as the PR for RN 0.61 gets merged, we can hopefully close this issue 🙂

**Comment by gamingumar** [comment] 2019-09-25 12:59
0.61 is released but I haven't yet tested. Hopefully it is resolved.

**Comment by radko93** [comment] 2019-09-26 12:57
I can confirm that this works with 0.61.1 so I'm closing this.

**Closed by radko93** 2019-09-26 12:57 UTC
